### ISSUE TITLE
question: 如何将日程往后延期若干天？

### ISSUE THREAD

**Issue by SilverRainZ** [trim21/bangumi-episode-calendar#153]
~~不懂 JS 只能伸手问了~~ RT，放送日不意味着当天就可以看上，在线党需要等网站上线 + 字幕组翻译，如何根据自己的需要往后延，例如说放送三日后再推送此日程。（需要自己部署亦可）。

**Comment by trim21** [comment]
https://github.com/trim21/bangumi-episode-calendar/blob/61f46f4e839610461c55153b2d30e9d617c44bdc/src/calendar.ts#L200-L209

把这里的 date 和 end 分别额外再加两天

**Comment by trim21** [comment]
想要自己部署的话可能有点麻烦，为了减少docker镜像的大小所以是先根据lock文件构建一个基础docker镜像，然后再构建完整的镜像。

需要fork之后需要改一下ci文件。

https://github.com/trim21/bangumi-episode-calendar/blob/master/.github/workflows/docker.yaml

除此之外还需要Redis来缓存数据。

**Comment by SilverRainZ** [comment]
Orz 听起来还蛮复杂我，我还以为是每个用户一个静态文件。

~那能把延迟做成可配置的么~

**Comment by trim21** [comment]
> Orz 听起来还蛮复杂的，我还以为是每个用户一个静态文件。
> 
> ~那能把延迟做成可配置的么~

你可以PR（
